cd

diff --git a/.github/workflows/android-cd.yml b/.github/workflows/android-cd.yml
--- a/.github/workflows/android-cd.yml
+++ b/.github/workflows/android-cd.yml
@@ -4,8 +4,10 @@ on:
   push:
     branches:
       - main  # Adjust the branch to your main branch
+
 permissions:
   contents: write  # Adjusting permissions for GITHUB_TOKEN
+
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -19,13 +21,10 @@ jobs:
           distribution: 'temurin'
       - name: Grant execute permission for Gradle wrapper
         run: chmod +x gradlew
-
       - name: Build with Gradle and Sign APK
         run: ./gradlew assembleRelease
-
       - name: Verify APK Path
         run: ls -R app/build/outputs/apk/release
-
       - name: Upload build artifacts
         uses: actions/upload-artifact@v2
         with:
@@ -42,13 +41,16 @@ jobs:
           name: app-release.apk
       - name: Install Firebase CLI
         run: npm install -g firebase-tools
-      - name: Navigate to project directory
-        run: |
-          cd .
-          ls -l
+      - name: Verify firebase.json presence
+        run: ls -l
+      - name: Display current directory
+        run: pwd
       - name: Deploy to Firebase
         env:
           FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
         run: |
-          firebase deploy --only hosting --token "${FIREBASE_TOKEN}"
-  
+          if [ ! -f firebase.json ]; then
+            echo "firebase.json not found!"
+            exit 1
+          fi
+          firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"
